# Generated by Django 3.2.6 on 2021-09-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nim',
        ),
    ]
