# Generated by Django 3.2.6 on 2021-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210930_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nim',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomor_hp',
            field=models.IntegerField(blank=True, default='', max_length=255, null=True),
        ),
    ]
