# Generated by Django 3.2.6 on 2021-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210930_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nim',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nomor_hp',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
