# Generated by Django 3.2.7 on 2021-10-01 20:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('kuliahpakar', tinymce.models.HTMLField(default='')),
                ('praktikum', tinymce.models.HTMLField(default='')),
                ('keterampilanmedis', tinymce.models.HTMLField(default='')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
