# Generated by Django 3.2.6 on 2021-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='', max_length=255)),
                ('deskripsi', models.CharField(default='', max_length=255)),
                ('konten', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
