# Generated by Django 3.2.6 on 2021-08-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='konten',
        ),
        migrations.AddField(
            model_name='materi',
            name='kuliahpakar',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materi',
            name='praktikum',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='materi',
            name='skillslab',
            field=models.TextField(default='', max_length=255),
        ),
    ]
