# Generated by Django 3.2.6 on 2021-08-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0002_auto_20210804_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='deskripsi',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='kuliahpakar',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='praktikum',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='skillslab',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
