# Generated by Django 3.2.6 on 2021-08-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0004_auto_20210804_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='kuliahpakar',
            field=models.TextField(blank=True, default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='materi',
            name='praktikum',
            field=models.TextField(blank=True, default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='materi',
            name='skillslab',
            field=models.TextField(blank=True, default='', max_length=9999),
        ),
    ]
