# Generated by Django 3.2.7 on 2021-10-10 21:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0004_jadwal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='keterampilanmedis',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materi',
            name='kuliahpakar',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materi',
            name='praktikum',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
