# Generated by Django 3.2.6 on 2021-08-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0005_auto_20210804_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
