# Generated by Django 3.2.6 on 2021-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0007_alter_materi_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='images/'),
        ),
    ]
