# Generated by Django 3.1.7 on 2021-08-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0008_alter_materi_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='thumbnail',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
