# Generated by Django 3.2.6 on 2021-08-18 03:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0009_auto_20210804_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='kuliahpakar',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
