# Generated by Django 3.2.6 on 2021-09-30 10:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fkuki2019', '0010_auto_20210818_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='praktikum',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='materi',
            name='skillslab',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
